name: Java CI sin Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Compilar clases
      run: |
        mkdir -p out
        javac -d out -cp "lib/" $(find src -name ".java")

    - name: Ejecutar tests con JUnit 5
      run: |
        java -jar lib/junit-platform-console-standalone-1.10.0.jar \
          --classpath out \
          --scan-class-path
